/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_constraint")
@Entity
public class Constraint extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String tableName;
	private String fieldName;
	private String constraint;
	private String message;

	public Constraint() {
	
	}

	public Constraint(Integer id){
		this.id = id;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="id", columnDefinition="int", nullable = false, length = 10)
	public Integer getId(){
		return id;
	}

	public void setId(Integer id){
		this.id = id;
	}
    
    @Column(name="table_name", columnDefinition="varchar", nullable = true, length = 50)
	public String getTableName(){
		return tableName;
	}

	public void setTableName(String tableName){
		this.tableName = tableName;
	}
    
    @Column(name="field_name", columnDefinition="varchar", nullable = true, length = 255)
	public String getFieldName(){
		return fieldName;
	}

	public void setFieldName(String fieldName){
		this.fieldName = fieldName;
	}
    
    @Column(name="constraint", columnDefinition="varchar", nullable = true, length = 255)
	public String getConstraint(){
		return constraint;
	}

	public void setConstraint(String constraint){
		this.constraint = constraint;
	}
    
    @Column(name="message", columnDefinition="varchar", nullable = true, length = 255)
	public String getMessage(){
		return message;
	}

	public void setMessage(String message){
		this.message = message;
	}
}
