/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_group")
@Entity
public class Group extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer parentId;
	private String name;
	private String description;
	private String code;
	private String role;
	private Short type;
	private Short status;
	private Integer sort;

	public Group() {
	
	}

	public Group(Integer id){
		this.id = id;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", columnDefinition="int", nullable = false, length = 10)
	public Integer getId(){
		return id;
	}

	public void setId(Integer id){
		this.id = id;
	}
    
    @Column(name = "parent_id", columnDefinition="int", nullable = true, length = 10)
	public Integer getParentId(){
		return parentId;
	}

	public void setParentId(Integer parentId){
		this.parentId = parentId;
	}
    
    @Column(name = "name", columnDefinition="varchar", nullable = true, length = 100)
	public String getName(){
		return name;
	}

	public void setName(String name){
		this.name = name;
	}
    
    @Column(name = "description", columnDefinition="varchar", nullable = true, length = 255)
	public String getDescription(){
		return description;
	}

	public void setDescription(String description){
		this.description = description;
	}
    
    @Column(name = "code", columnDefinition="varchar", nullable = true, length = 50)
	public String getCode(){
		return code;
	}

	public void setCode(String code){
		this.code = code;
	}
    
    @Column(name = "role", columnDefinition="varchar", nullable = true, length = 20)
	public String getRole(){
		return role;
	}

	public void setRole(String role){
		this.role = role;
	}
    
    @Column(name = "type", columnDefinition="tinyint", nullable = true, length = 3)
	public Short getType(){
		return type;
	}

	public void setType(Short type){
		this.type = type;
	}
    
    @Column(name = "status", columnDefinition="tinyint", nullable = true, length = 3)
	public Short getStatus(){
		return status;
	}

	public void setStatus(Short status){
		this.status = status;
	}
    
    @Column(name = "sort", columnDefinition="int", nullable = true, length = 10)
	public Integer getSort(){
		return sort;
	}

	public void setSort(Integer sort){
		this.sort = sort;
	}
}
