/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_module")
@Entity
public class Module extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer parentId;
	private String name;
	private String path;
	private String description;
	private String code;
	private Integer sort;
	private String href;
	private String target;
	private String icon;
	private String visible;
	private String permission;
	private String createBy;
	private Date createTime;
	private String updateBy;
	private Date updateTime;
	private String deleted;

	public Module() {
	
	}

	public Module(Integer id){
		this.id = id;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="id", columnDefinition="int", nullable = false, length = 10)
	public Integer getId(){
		return id;
	}

	public void setId(Integer id){
		this.id = id;
	}
    
    @Column(name="parent_id", columnDefinition="int", nullable = false, length = 10)
	public Integer getParentId(){
		return parentId;
	}

	public void setParentId(Integer parentId){
		this.parentId = parentId;
	}
    
    @Column(name="name", columnDefinition="varchar", nullable = false, length = 100)
	public String getName(){
		return name;
	}

	public void setName(String name){
		this.name = name;
	}
    
    @Column(name="path", columnDefinition="varchar", nullable = false, length = 255)
	public String getPath(){
		return path;
	}

	public void setPath(String path){
		this.path = path;
	}
    
    @Column(name="description", columnDefinition="varchar", nullable = true, length = 255)
	public String getDescription(){
		return description;
	}

	public void setDescription(String description){
		this.description = description;
	}
    
    @Column(name="code", columnDefinition="varchar", nullable = true, length = 50)
	public String getCode(){
		return code;
	}

	public void setCode(String code){
		this.code = code;
	}
    
    @Column(name="sort", columnDefinition="int", nullable = true, length = 10)
	public Integer getSort(){
		return sort;
	}

	public void setSort(Integer sort){
		this.sort = sort;
	}
    
    @Column(name="href", columnDefinition="varchar", nullable = true, length = 255)
	public String getHref(){
		return href;
	}

	public void setHref(String href){
		this.href = href;
	}
    
    @Column(name="target", columnDefinition="varchar", nullable = true, length = 20)
	public String getTarget(){
		return target;
	}

	public void setTarget(String target){
		this.target = target;
	}
    
    @Column(name="icon", columnDefinition="varchar", nullable = true, length = 100)
	public String getIcon(){
		return icon;
	}

	public void setIcon(String icon){
		this.icon = icon;
	}
    
    @Column(name="visible", columnDefinition="char", nullable = false, length = 1)
	public String getVisible(){
		return visible;
	}

	public void setVisible(String visible){
		this.visible = visible;
	}
    
    @Column(name="permission", columnDefinition="varchar", nullable = true, length = 200)
	public String getPermission(){
		return permission;
	}

	public void setPermission(String permission){
		this.permission = permission;
	}
    
    @Column(name="create_by", columnDefinition="varchar", nullable = false, length = 50)
	public String getCreateBy(){
		return createBy;
	}

	public void setCreateBy(String createBy){
		this.createBy = createBy;
	}
    
    @Column(name="create_time", columnDefinition="datetime", nullable = false, length = 19)
	public Date getCreateTime(){
		return createTime;
	}

	public void setCreateTime(Date createTime){
		this.createTime = createTime;
	}
    
    @Column(name="update_by", columnDefinition="varchar", nullable = false, length = 50)
	public String getUpdateBy(){
		return updateBy;
	}

	public void setUpdateBy(String updateBy){
		this.updateBy = updateBy;
	}
    
    @Column(name="update_time", columnDefinition="datetime", nullable = false, length = 19)
	public Date getUpdateTime(){
		return updateTime;
	}

	public void setUpdateTime(Date updateTime){
		this.updateTime = updateTime;
	}
    
    @Column(name="deleted", columnDefinition="char", nullable = false, length = 1)
	public String getDeleted(){
		return deleted;
	}

	public void setDeleted(String deleted){
		this.deleted = deleted;
	}
}
