/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_permission")
@Entity
public class Permission extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String object;
	private String operation;
	private String description;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private String deleted;

	public Permission() {
	
	}

	public Permission(Integer id){
		this.id = id;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", columnDefinition="int", nullable = false, length = 10)
	public Integer getId(){
		return id;
	}

	public void setId(Integer id){
		this.id = id;
	}
    
    @Column(name = "object", columnDefinition="varchar", nullable = true, length = 255)
	public String getObject(){
		return object;
	}

	public void setObject(String object){
		this.object = object;
	}
    
    @Column(name = "operation", columnDefinition="varchar", nullable = true, length = 255)
	public String getOperation(){
		return operation;
	}

	public void setOperation(String operation){
		this.operation = operation;
	}
    
    @Column(name = "description", columnDefinition="varchar", nullable = true, length = 255)
	public String getDescription(){
		return description;
	}

	public void setDescription(String description){
		this.description = description;
	}
    
    @Column(name = "create_by", columnDefinition="varchar", nullable = true, length = 64)
	public String getCreateBy(){
		return createBy;
	}

	public void setCreateBy(String createBy){
		this.createBy = createBy;
	}
    
    @Column(name = "create_date", columnDefinition="datetime", nullable = true, length = 19)
	public Date getCreateDate(){
		return createDate;
	}

	public void setCreateDate(Date createDate){
		this.createDate = createDate;
	}
    
    @Column(name = "update_by", columnDefinition="varchar", nullable = true, length = 64)
	public String getUpdateBy(){
		return updateBy;
	}

	public void setUpdateBy(String updateBy){
		this.updateBy = updateBy;
	}
    
    @Column(name = "update_date", columnDefinition="datetime", nullable = true, length = 19)
	public Date getUpdateDate(){
		return updateDate;
	}

	public void setUpdateDate(Date updateDate){
		this.updateDate = updateDate;
	}
    
    @Column(name = "deleted", columnDefinition="char", nullable = true, length = 1)
	public String getDeleted(){
		return deleted;
	}

	public void setDeleted(String deleted){
		this.deleted = deleted;
	}
}
