/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_role_permission")
@Entity
public class RolePermission extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer roleId;
	private String permission;

	public RolePermission() {
	
	}

	public RolePermission(Integer id){
		this.id = id;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="id", columnDefinition="int", nullable = false, length = 10)
	public Integer getId(){
		return id;
	}

	public void setId(Integer id){
		this.id = id;
	}
    
    @Column(name="role_id", columnDefinition="int", nullable = true, length = 10)
	public Integer getRoleId(){
		return roleId;
	}

	public void setRoleId(Integer roleId){
		this.roleId = roleId;
	}
    
    @Column(name="permission", columnDefinition="varchar", nullable = true, length = 255)
	public String getPermission(){
		return permission;
	}

	public void setPermission(String permission){
		this.permission = permission;
	}
}
