/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_role_menu")
@Entity
public class RoleMenu extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer roleId;
	private Integer menuId;

	public RoleMenu() {
	
	}

	public RoleMenu(Integer menuId){
		this.menuId = menuId;
	}
    
    @Column(name = "role_id", columnDefinition="int", nullable = false, length = 10)
	public Integer getRoleId(){
		return roleId;
	}

	public void setRoleId(Integer roleId){
		this.roleId = roleId;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "menu_id", columnDefinition="int", nullable = false, length = 10)
	public Integer getMenuId(){
		return menuId;
	}

	public void setMenuId(Integer menuId){
		this.menuId = menuId;
	}
}
