/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_table_log")
@Entity
public class TableLog extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer tableId;
	private Integer rowId;
	private Integer createBy;
	private Date createTime;
	private Integer updateBy;
	private Date updateTime;
	private String deleted;

	public TableLog() {
	
	}

	public TableLog(Integer id){
		this.id = id;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="id", columnDefinition="int", nullable = false, length = 10)
	public Integer getId(){
		return id;
	}

	public void setId(Integer id){
		this.id = id;
	}
    
    @Column(name="table_id", columnDefinition="int", nullable = true, length = 10)
	public Integer getTableId(){
		return tableId;
	}

	public void setTableId(Integer tableId){
		this.tableId = tableId;
	}
    
    @Column(name="row_id", columnDefinition="int", nullable = true, length = 10)
	public Integer getRowId(){
		return rowId;
	}

	public void setRowId(Integer rowId){
		this.rowId = rowId;
	}
    
    @Column(name="create_by", columnDefinition="int", nullable = true, length = 10)
	public Integer getCreateBy(){
		return createBy;
	}

	public void setCreateBy(Integer createBy){
		this.createBy = createBy;
	}
    
    @Column(name="create_time", columnDefinition="datetime", nullable = true, length = 19)
	public Date getCreateTime(){
		return createTime;
	}

	public void setCreateTime(Date createTime){
		this.createTime = createTime;
	}
    
    @Column(name="update_by", columnDefinition="int", nullable = true, length = 10)
	public Integer getUpdateBy(){
		return updateBy;
	}

	public void setUpdateBy(Integer updateBy){
		this.updateBy = updateBy;
	}
    
    @Column(name="update_time", columnDefinition="datetime", nullable = true, length = 19)
	public Date getUpdateTime(){
		return updateTime;
	}

	public void setUpdateTime(Date updateTime){
		this.updateTime = updateTime;
	}
    
    @Column(name="deleted", columnDefinition="char", nullable = true, length = 1)
	public String getDeleted(){
		return deleted;
	}

	public void setDeleted(String deleted){
		this.deleted = deleted;
	}
}
