/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_user")
@Entity
public class User extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private String password;
	private Integer type;
	private Integer status;
	private String loginName;
	private String loginIp;
	private Date loginTime;
	private String loginAllow;
	private Integer visitCount;
	private String registerTime;
	private String createBy;
	private Date createTime;
	private String updateBy;
	private Date updateTime;
	private String deleted;
	private String remark;

	public User() {
	
	}

	public User(Integer id){
		this.id = id;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="id", columnDefinition="int", nullable = false, length = 10)
	public Integer getId(){
		return id;
	}

	public void setId(Integer id){
		this.id = id;
	}
    
    @Column(name="name", columnDefinition="varchar", nullable = false, length = 64)
	public String getName(){
		return name;
	}

	public void setName(String name){
		this.name = name;
	}
    
    @Column(name="password", columnDefinition="varchar", nullable = false, length = 20)
	public String getPassword(){
		return password;
	}

	public void setPassword(String password){
		this.password = password;
	}
    
    @Column(name="type", columnDefinition="int", nullable = true, length = 10)
	public Integer getType(){
		return type;
	}

	public void setType(Integer type){
		this.type = type;
	}
    
    @Column(name="status", columnDefinition="int", nullable = true, length = 10)
	public Integer getStatus(){
		return status;
	}

	public void setStatus(Integer status){
		this.status = status;
	}
    
    @Column(name="login_name", columnDefinition="varchar", nullable = true, length = 255)
	public String getLoginName(){
		return loginName;
	}

	public void setLoginName(String loginName){
		this.loginName = loginName;
	}
    
    @Column(name="login_ip", columnDefinition="varchar", nullable = true, length = 20)
	public String getLoginIp(){
		return loginIp;
	}

	public void setLoginIp(String loginIp){
		this.loginIp = loginIp;
	}
    
    @Column(name="login_time", columnDefinition="datetime", nullable = true, length = 19)
	public Date getLoginTime(){
		return loginTime;
	}

	public void setLoginTime(Date loginTime){
		this.loginTime = loginTime;
	}
    
    @Column(name="login_allow", columnDefinition="char", nullable = true, length = 1)
	public String getLoginAllow(){
		return loginAllow;
	}

	public void setLoginAllow(String loginAllow){
		this.loginAllow = loginAllow;
	}
    
    @Column(name="visit_count",  nullable = true, length = 10)
	public Integer getVisitCount(){
		return visitCount;
	}

	public void setVisitCount(Integer visitCount){
		this.visitCount = visitCount;
	}
    
    @Column(name="register_time", columnDefinition="varchar", nullable = true, length = 255)
	public String getRegisterTime(){
		return registerTime;
	}

	public void setRegisterTime(String registerTime){
		this.registerTime = registerTime;
	}
    
    @Column(name="create_by", columnDefinition="varchar", nullable = true, length = 64)
	public String getCreateBy(){
		return createBy;
	}

	public void setCreateBy(String createBy){
		this.createBy = createBy;
	}
    
    @Column(name="create_time", columnDefinition="datetime", nullable = true, length = 19)
	public Date getCreateTime(){
		return createTime;
	}

	public void setCreateTime(Date createTime){
		this.createTime = createTime;
	}
    
    @Column(name="update_by", columnDefinition="varchar", nullable = true, length = 64)
	public String getUpdateBy(){
		return updateBy;
	}

	public void setUpdateBy(String updateBy){
		this.updateBy = updateBy;
	}
    
    @Column(name="update_time", columnDefinition="datetime", nullable = true, length = 19)
	public Date getUpdateTime(){
		return updateTime;
	}

	public void setUpdateTime(Date updateTime){
		this.updateTime = updateTime;
	}
    
    @Column(name="deleted", columnDefinition="char", nullable = true, length = 1)
	public String getDeleted(){
		return deleted;
	}

	public void setDeleted(String deleted){
		this.deleted = deleted;
	}
    
    @Column(name="remark", columnDefinition="varchar", nullable = true, length = 255)
	public String getRemark(){
		return remark;
	}

	public void setRemark(String remark){
		this.remark = remark;
	}
}
