/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_user_detail")
@Entity
public class UserDetail extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer userId;
	private Integer orgId;
	private Integer groupId;
	private String nick;
	private String ename;
	private String avatar;
	private String sex;
	private Date birthday;

	public UserDetail() {
	
	}

	public UserDetail(Integer id){
		this.id = id;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", columnDefinition="int", nullable = false, length = 10)
	public Integer getId(){
		return id;
	}

	public void setId(Integer id){
		this.id = id;
	}
    
    @Column(name = "user_id", columnDefinition="int", nullable = false, length = 10)
	public Integer getUserId(){
		return userId;
	}

	public void setUserId(Integer userId){
		this.userId = userId;
	}
    
    @Column(name = "org_id", columnDefinition="int", nullable = true, length = 10)
	public Integer getOrgId(){
		return orgId;
	}

	public void setOrgId(Integer orgId){
		this.orgId = orgId;
	}
    
    @Column(name = "group_id", columnDefinition="int", nullable = true, length = 10)
	public Integer getGroupId(){
		return groupId;
	}

	public void setGroupId(Integer groupId){
		this.groupId = groupId;
	}
    
    @Column(name = "nick", columnDefinition="varchar", nullable = true, length = 255)
	public String getNick(){
		return nick;
	}

	public void setNick(String nick){
		this.nick = nick;
	}
    
    @Column(name = "ename", columnDefinition="varchar", nullable = true, length = 255)
	public String getEname(){
		return ename;
	}

	public void setEname(String ename){
		this.ename = ename;
	}
    
    @Column(name = "avatar", columnDefinition="varchar", nullable = true, length = 255)
	public String getAvatar(){
		return avatar;
	}

	public void setAvatar(String avatar){
		this.avatar = avatar;
	}
    
    @Column(name = "sex", columnDefinition="varchar", nullable = true, length = 1)
	public String getSex(){
		return sex;
	}

	public void setSex(String sex){
		this.sex = sex;
	}
    
    @Column(name = "birthday", columnDefinition="datetime", nullable = true, length = 19)
	public Date getBirthday(){
		return birthday;
	}

	public void setBirthday(Date birthday){
		this.birthday = birthday;
	}
}
