/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_user_org")
@Entity
public class UserOrg extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer userId;
	private Integer orgId;
	private String createBy;
	private Date createTime;
	private String updateBy;
	private Date updateTime;
	private String deleted;

	public UserOrg() {
	
	}

	public UserOrg(Integer id){
		this.id = id;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="id", columnDefinition="int", nullable = false, length = 10)
	public Integer getId(){
		return id;
	}

	public void setId(Integer id){
		this.id = id;
	}
    
    @Column(name="user_id", columnDefinition="int", nullable = true, length = 10)
	public Integer getUserId(){
		return userId;
	}

	public void setUserId(Integer userId){
		this.userId = userId;
	}
    
    @Column(name="org_id", columnDefinition="int", nullable = true, length = 10)
	public Integer getOrgId(){
		return orgId;
	}

	public void setOrgId(Integer orgId){
		this.orgId = orgId;
	}
    
    @Column(name="create_by", columnDefinition="varchar", nullable = true, length = 50)
	public String getCreateBy(){
		return createBy;
	}

	public void setCreateBy(String createBy){
		this.createBy = createBy;
	}
    
    @Column(name="create_time", columnDefinition="datetime", nullable = true, length = 19)
	public Date getCreateTime(){
		return createTime;
	}

	public void setCreateTime(Date createTime){
		this.createTime = createTime;
	}
    
    @Column(name="update_by", columnDefinition="varchar", nullable = true, length = 50)
	public String getUpdateBy(){
		return updateBy;
	}

	public void setUpdateBy(String updateBy){
		this.updateBy = updateBy;
	}
    
    @Column(name="update_time", columnDefinition="datetime", nullable = true, length = 19)
	public Date getUpdateTime(){
		return updateTime;
	}

	public void setUpdateTime(Date updateTime){
		this.updateTime = updateTime;
	}
    
    @Column(name="deleted", columnDefinition="char", nullable = true, length = 1)
	public String getDeleted(){
		return deleted;
	}

	public void setDeleted(String deleted){
		this.deleted = deleted;
	}
}
