/*
 * Copyright (C) 2016-2017 Spring Agile. All rights reserved.
 * Licensed under the Apache License, Version 2.0
 */
package com.agile.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import com.agile.framework.persistence.BaseEntity;

// THIS CODE IS GENERATED BY CODE GENERATOR.

@Table(name="sys_user_contact")
@Entity
public class UserContact extends BaseEntity {
	
	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private Integer userId;
	private Integer type;
	private String tool;
	private String number;

	public UserContact() {
	
	}

	public UserContact(Integer id){
		this.id = id;
	}
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", columnDefinition="int", nullable = false, length = 10)
	public Integer getId(){
		return id;
	}

	public void setId(Integer id){
		this.id = id;
	}
    
    @Column(name = "user_id", columnDefinition="int", nullable = false, length = 10)
	public Integer getUserId(){
		return userId;
	}

	public void setUserId(Integer userId){
		this.userId = userId;
	}
    
    @Column(name = "type", columnDefinition="int", nullable = true, length = 10)
	public Integer getType(){
		return type;
	}

	public void setType(Integer type){
		this.type = type;
	}
    
    @Column(name = "tool", columnDefinition="varchar", nullable = true, length = 64)
	public String getTool(){
		return tool;
	}

	public void setTool(String tool){
		this.tool = tool;
	}
    
    @Column(name = "number", columnDefinition="varchar", nullable = true, length = 64)
	public String getNumber(){
		return number;
	}

	public void setNumber(String number){
		this.number = number;
	}
}
